config/routes.rb
Rails.application.routes.draw do
  #Root
  root to: "welcome#index"

  #Routes for Traits
  get "/traits", to: "traits#index", as:"traits"

  #Routes for Emperor
  get "/emperors", to:"emperors#index", as:"emperors"
  get "/emperors/:id", to:"emperors#show", as:"emperor"
end

app/models/emperor.rb
class Emperor < ActiveRecord::Base
	has_many :traits
end

app/models/porcelain.rb
class Porcelain < ActiveRecord::Base
end

app/models/trait.rb
class Trait < ActiveRecord::Base
	belongs_to :emperor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emperors_controller.rb
class EmperorsController < ApplicationController

	def index
		@emperors = Emperor.all
		render :index
	end

	def show
		@emperor = Emperor.find_by_id(params[:id])
	end

end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
	
	def index
		@traits = Trait.all

		render :index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emperors_helper.rb
module EmperorsHelper
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/emperors/index.html.erb
<br>
<br>
<br>

<div class="container">
	<h3 class="text-center">Ming Dynasty</h3>
</div>

	<% @emperors.each do |emperor| %>
		<div class="container">
		  <p class="text-center">
		    <strong>Name:</strong> <%=emperor.name%><br>
		    <strong>Year:</strong> <%=emperor.year%><br>
		  </p>
		</div>
	<% end %>

app/views/emperors/show.html.erb
<br>
<br>  
<br>
  <% emperor=@emperor %>

  <p class="text-center">
    <strong>Name:</strong> <%=emperor.name%><br>
    <strong>Picture:</strong> Placeholder for Picture<br>
    <strong>Year:</strong> <%=emperor.year%><br>
    <strong>Dynasty:</strong> <%=emperor.dynasty%><br>
    <strong>Description:</strong> Placeholder for Description of Emperor<br>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Antiques</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- custom styles (always require after Bootstrap) -->
  <link rel="stylesheet" href="style.css">

</head>
<body>
	<!-- Start of Navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Antique Database</a>
    </div>
    <div class="collapse navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">  
      	<li><%= link_to "TRAITS", traits_path %></li>  
      	<li><%= link_to "EMPERORS", emperors_path %></li>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
<!-- End of Navbar -->

<%= yield %>

</body>
</html>

app/views/traits/index.html.erb
<br>
<br>
<!-- Find a better way to add space to the top-->

<div class="container">
	<h3 class="text-center">Singular Traits</h3>
</div>

	<% @traits.each do |trait| %>
		<div class="container">
		  <p class="text-center">
		    <strong>Name:</strong> <%=link_to trait.name, emperor_path(trait.emperor_id) %><br>
		  </p>
		</div>
	<% end %>